### ISSUE TITLE
Upgrade Files Checklist

### ISSUE THREAD

**Issue by andympd** [relaciones-internacionales-journal/OJS-2.4.6#1]
- [x] ojs\lib\pkp\classes\oai\OAI.inc.php 
- [x] ojs\lib\pkp\classes\oai\OAIStruct.inc.php 
- [x] ojs\lib\pkp\classes\oai\OAIUtils.inc.php 
- [x] ojs\lib\pkp\locale\en_US\common.xml 
- [x] ojs\lib\pkp\locale\en_US\reader.xml 
- [x] ojs\lib\pkp\locale\en_US\submission.xml 
- [x] ojs\lib\pkp\locale\es_ES\common.xml 
- [x] ojs\lib\pkp\locale\es_ES\manager.xml 
- [x] ojs\lib\pkp\locale\es_ES\reader.xml 
- [x] ojs\lib\pkp\locale\es_ES\submission.xml 
- [x] ojs\lib\pkp\templates\announcement\index.tpl 
- [x] ojs\lib\pkp\templates\announcement\list.tpl 
- [x] ojs\lib\pkp\templates\announcement\view.tpl 
- [x] ojs\lib\pkp\templates\common\breadcrumbs.tpl 
- [x] ojs\lib\pkp\templates\common\footer.tpl 
- [x] ojs\lib\pkp\templates\common\formErrors.tpl 
- [x] ojs\lib\pkp\templates\common\header.tpl 
- [x] ojs\lib\pkp\templates\email\email.tpl 
- [x] ojs\lib\pkp\templates\help\footer.tpl 
- [x] ojs\lib\pkp\templates\help\header.tpl 
- [x] ojs\lib\pkp\templates\help\helpToc.tpl 
- [x] ojs\lib\pkp\templates\help\searchResults.tpl 
- [x] ojs\lib\pkp\templates\help\topic.tpl 
- [x] ojs\lib\pkp\templates\help\view.tpl 
- [x] ojs\lib\pkp\templates\manager\announcement\announcementForm.tpl 
- [x] ojs\lib\pkp\templates\manager\announcement\announcements.tpl 
- [x] ojs\lib\pkp\templates\manager\announcement\announcementTypeForm.tpl 
- [x] ojs\lib\pkp\templates\manager\announcement\announcementTypes.tpl 
- [x] ojs\lib\pkp\templates\user\login.tpl 
- [x] ojs\lib\pkp\templates\user\loginChangePassword.tpl 
- [x] ojs\lib\pkp\templates\user\lostPassword.tpl 
- [x] ojs\locale\en_US\author.xml 
- [x] ojs\locale\en_US\locale.xml 
- [x] ojs\locale\es_ES\author.xml 
- [x] ojs\locale\es_ES\locale.xml 
- [x] ojs\locale\es_ES\manager.xml 
- [x] ojs\pages\about\AboutHandler.inc.php 
- [x] ojs\plugins\blocks\authorBios\block.tpl 
- [x] ojs\plugins\blocks\keywordCloud\block.tpl 
- [x] ojs\plugins\blocks\keywordCloud\KeywordCloudBlockPlugin.inc.php 
- [x] ojs\plugins\blocks\languageToggle\block.tpl 
- [x] ojs\plugins\blocks\navigation\block.tpl 
- [x] ojs\plugins\blocks\navigation\locale\en_US\locale.xml 
- [x] ojs\plugins\blocks\navigation\locale\es_ES\locale.xml 
- [x] ojs\plugins\blocks\readingTools\block.tpl 
- [x] ojs\plugins\blocks\readingTools\locale\en_US\locale.xml 
- [x] ojs\plugins\blocks\relatedItems\block.tpl 
- [x] ojs\plugins\blocks\relatedItems\locale\en_US\locale.xml 
- [x] ojs\plugins\blocks\relatedItems\locale\es_ES\locale.xml 
- [x] ojs\plugins\blocks\user\block.tpl 
- [x] ojs\plugins\blocks\user\locale\en_US\locale.xml 
- [x] ojs\plugins\blocks\user\locale\es_ES\locale.xml 
- [x] ojs\plugins\citationFormats\refWorks\citation.tpl 
- [x] ojs\plugins\generic\announcementFeed\templates\block.tpl 
- [x] ojs\plugins\generic\googleViewer\index.tpl 
- [x] ojs\plugins\generic\staticPages\editStaticPageForm.tpl 
- [x] ojs\plugins\generic\staticPages\settingsForm.tpl 
- [x] ojs\styles\comments.css 
- [x] ojs\templates\about\contact.tpl 
- [x] ojs\templates\about\editorialPolicies.tpl 
- [x] ojs\templates\about\editorialTeamBoard.tpl 
- [x] ojs\templates\about\index.tpl 
- [x] ojs\templates\about\journalSponsorship.tpl 
- [x] ojs\templates\about\submissions.tpl 
- [x] ojs\templates\admin\auth\sources.tpl 
- [x] ojs\templates\admin\categories\categories.tpl 
- [x] ojs\templates\admin\index.tpl 
- [x] ojs\templates\admin\journals.tpl 
- [x] ojs\templates\admin\journalSettings.tpl 
- [x] ojs\templates\admin\languages.tpl 
- [x] ojs\templates\admin\selectMergeUser.tpl 
- [x] ojs\templates\admin\settings.tpl 
- [x] ojs\templates\admin\systemInfo.tpl 
- [x] ojs\templates\article\article.tpl 
- [x] ojs\templates\article\footer.tpl 
- [x] ojs\templates\article\header.tpl 
- [x] ojs\templates\article\pdfViewer.tpl 
- [x] ojs\templates\author\active.tpl 
- [x] ojs\templates\author\completed.tpl 
- [x] ojs\templates\author\index.tpl 
- [x] ojs\templates\author\submission\copyedit.tpl 
- [x] ojs\templates\author\submission\editorDecision.tpl 
- [x] ojs\templates\author\submission\management.tpl 
- [x] ojs\templates\author\submission\peerReview.tpl 
- [x] ojs\templates\author\submission\proofread.tpl 
- [x] ojs\templates\author\submission\status.tpl 
- [x] ojs\templates\author\submission\summary.tpl 
- [x] ojs\templates\author\submissionEditing.tpl 
- [x] ojs\templates\author\submissionReview.tpl 
- [x] ojs\templates\author\submit\complete.tpl 
- [x] ojs\templates\author\submit\step1.tpl 
- [x] ojs\templates\author\submit\step2.tpl 
- [x] ojs\templates\author\submit\step3.tpl 
- [x] ojs\templates\author\submit\step4.tpl 
- [x] ojs\templates\author\submit\step5.tpl 
- [x] ojs\templates\author\submit\submitHeader.tpl 
- [x] ojs\templates\author\submit\suppFile.tpl 
- [x] ojs\templates\citation\citationEditor.tpl 
- [x] ojs\templates\editor\index.tpl 
- [x] ojs\templates\editor\issues\backIssues.tpl 
- [x] ojs\templates\editor\issues\createIssue.tpl 
- [x] ojs\templates\editor\issues\futureIssues.tpl 
- [x] ojs\templates\editor\issues\issueData.tpl 
- [x] ojs\templates\editor\issues\issueGalleys.tpl 
- [x] ojs\templates\editor\issues\issueToc.tpl 
- [x] ojs\templates\editor\notifyUsers.tpl 
- [x] ojs\templates\editor\selectSectionEditor.tpl 
- [x] ojs\templates\editor\submissions.tpl 
- [x] ojs\templates\editor\submissionsArchives.tpl 
- [x] ojs\templates\editor\submissionsInEditing.tpl 
- [x] ojs\templates\editor\submissionsInReview.tpl 
- [x] ojs\templates\editor\submissionsUnassigned.tpl 
- [x] ojs\templates\index\journal.tpl 
- [x] ojs\templates\issue\archive.tpl 
- [x] ojs\templates\issue\issue.tpl 
- [x] ojs\templates\issue\view.tpl 
- [x] ojs\templates\manager\emails\emails.tpl 
- [x] ojs\templates\manager\emails\emailTemplateForm.tpl 
- [x] ojs\templates\manager\files\index.tpl 
- [x] ojs\templates\manager\groups\groupForm.tpl 
- [x] ojs\templates\manager\groups\groups.tpl 
- [x] ojs\templates\manager\groups\memberships.tpl 
- [x] ojs\templates\manager\importexport\plugins.tpl 
- [x] ojs\templates\manager\index.tpl 
- [x] ojs\templates\manager\languageSettings.tpl 
- [x] ojs\templates\manager\people\enrollment.tpl 
- [x] ojs\templates\manager\people\searchUsers.tpl 
- [x] ojs\templates\manager\people\selectMergeUser.tpl 
- [x] ojs\templates\manager\people\userProfile.tpl 
- [x] ojs\templates\manager\people\userProfileForm.tpl 
- [x] ojs\templates\manager\plugins\plugins.tpl 
- [x] ojs\templates\manager\reviewForms\previewReviewForm.tpl 
- [x] ojs\templates\manager\reviewForms\reviewFormElementForm.tpl 
- [x] ojs\templates\manager\reviewForms\reviewFormElements.tpl 
- [x] ojs\templates\manager\reviewForms\reviewFormForm.tpl 
- [x] ojs\templates\manager\reviewForms\reviewForms.tpl 
- [x] ojs\templates\manager\sections\sectionForm.tpl 
- [x] ojs\templates\manager\sections\sections.tpl 
- [x] ojs\templates\manager\setup\index.tpl 
- [x] ojs\templates\manager\setup\setupHeader.tpl 
- [x] ojs\templates\manager\setup\step1.tpl 
- [x] ojs\templates\manager\setup\step2.tpl 
- [x] ojs\templates\manager\setup\step3.tpl 
- [x] ojs\templates\manager\setup\step4.tpl 
- [x] ojs\templates\manager\setup\step5.tpl 
- [x] ojs\templates\manager\statistics\index.tpl 
- [x] ojs\templates\manager\statistics\statistics.tpl 
- [x] ojs\templates\reviewer\active.tpl 
- [x] ojs\templates\reviewer\completed.tpl 
- [x] ojs\templates\reviewer\index.tpl 
- [x] ojs\templates\reviewer\submission.tpl 
- [x] ojs\templates\rt\context.tpl 
- [x] ojs\templates\rt\findingReferences.tpl 
- [x] ojs\templates\rt\footer.tpl 
- [x] ojs\templates\rt\header.tpl 
- [x] ojs\templates\rt\suppFiles.tpl 
- [x] ojs\templates\rtadmin\index.tpl 
- [x] ojs\templates\search\authorDetails.tpl 
- [x] ojs\templates\search\authorIndex.tpl 
- [x] ojs\templates\search\search.tpl 
- [x] ojs\templates\search\titleIndex.tpl 
- [x] ojs\templates\sectionEditor\createReviewerForm.tpl 
- [x] ojs\templates\sectionEditor\index.tpl 
- [x] ojs\templates\sectionEditor\reviewerRecommendation.tpl 
- [x] ojs\templates\sectionEditor\searchUsers.tpl 
- [x] ojs\templates\sectionEditor\selectReviewer.tpl 
- [x] ojs\templates\sectionEditor\selectReviewForm.tpl 
- [x] ojs\templates\sectionEditor\setDueDate.tpl 
- [x] ojs\templates\sectionEditor\submission\copyedit.tpl 
- [x] ojs\templates\sectionEditor\submission\editorDecision.tpl 
- [x] ojs\templates\sectionEditor\submission\editors.tpl 
- [x] ojs\templates\sectionEditor\submission\layout.tpl 
- [x] ojs\templates\sectionEditor\submission\management.tpl 
- [x] ojs\templates\sectionEditor\submission\peerReview.tpl 
- [x] ojs\templates\sectionEditor\submission\proofread.tpl 
- [x] ojs\templates\sectionEditor\submission\rounds.tpl 
- [x] ojs\templates\sectionEditor\submission\scheduling.tpl 
- [x] ojs\templates\sectionEditor\submission\status.tpl 
- [x] ojs\templates\sectionEditor\submission\summary.tpl 
- [x] ojs\templates\sectionEditor\submission.tpl 
- [x] ojs\templates\sectionEditor\submissionCitations.tpl 
- [x] ojs\templates\sectionEditor\submissionEditing.tpl 
- [x] ojs\templates\sectionEditor\submissionEmailLog.tpl 
- [x] ojs\templates\sectionEditor\submissionEmailLogEntry.tpl 
- [x] ojs\templates\sectionEditor\submissionEventLog.tpl 
- [x] ojs\templates\sectionEditor\submissionEventLogEntry.tpl 
- [x] ojs\templates\sectionEditor\submissionHistory.tpl 
- [x] ojs\templates\sectionEditor\submissionNotes.tpl 
- [x] ojs\templates\sectionEditor\submissionRegrets.tpl 
- [x] ojs\templates\sectionEditor\submissionReview.tpl 
- [x] ojs\templates\submission\comment\comment.tpl 
- [x] ojs\templates\submission\comment\editComment.tpl 
- [x] ojs\templates\submission\comment\editorDecisionComment.tpl 
- [x] ojs\templates\submission\comment\editorDecisionEmail.tpl 
- [x] ojs\templates\submission\comment\footer.tpl 
- [x] ojs\templates\submission\comment\header.tpl 
- [x] ojs\templates\submission\comment\peerReviewComment.tpl 
- [x] ojs\templates\submission\instructions.tpl 
- [x] ojs\templates\submission\layout\galleyForm.tpl 
- [x] ojs\templates\submission\metadata\metadata.tpl 
- [x] ojs\templates\submission\metadata\metadataEdit.tpl 
- [x] ojs\templates\submission\reviewForm\reviewFormResponse.tpl 
- [x] ojs\templates\submission\suppFile\suppFile.tpl 
- [x] ojs\templates\user\changePassword.tpl 
- [x] ojs\templates\user\index.tpl 
- [x] ojs\templates\user\profile.tpl 
- [x] ojs\templates\user\register.tpl
